In [1]:
%load_ext autoreload
%autoreload 2

In [8]:
# Imports
import sys
from pathlib import Path
from art.attacks.evasion import FastGradientMethod, ProjectedGradientDescent, SaliencyMapMethod, CarliniL2Method

sys.path.append(str(Path.cwd().parents[1]))

from utils.functions import get_windowed_data
from utils.notebook import get_model_classifier, clean_data_test, adv_test, FilenameLoader
from MBD_systems.windowed_eval import split_csv_by_sender_receiver

In [6]:
## Inputs
checkpoint_name, data_name, save_name = FilenameLoader.const_pos()

checkpoint_file= f"../../../saved_models/{checkpoint_name}"
data_file = f"../../data/{data_name}"
save_path = f"../final_data/{save_name}"

collapsed = True # True for JSMA and CW
save_clean = False

In [12]:
pairs = split_csv_by_sender_receiver(Path(data_file), 
                                    tmp_dir=Path("./temp")
                                    )

In [ ]:
## Load model and data
# Load original model and ART-wrapper classifier
# model, classifier = get_model_classifier(checkpoint_file, collapsed)

# Load data
(x_train, y_train), (x_test, y_test), fed_dataset, scaler = get_windowed_data(data_file, 
                                                                      normalize=True, 
                                                                      train_perc=80)

In [ ]:
## DO NOT OPEN THE ./temp folder !!!! IT HAS A LOTTT OF PAIRS

In [ ]:
pairs
# hardcode for now - 9, 21

[(9, 21),
 (9, 45),
 (9, 63),
 (9, 75),
 (9, 99),
 (9, 147),
 (9, 189),
 (9, 219),
 (9, 225),
 (15, 21),
 (15, 27),
 (21, 9),
 (21, 15),
 (21, 27),
 (21, 63),
 (21, 75),
 (21, 99),
 (21, 111),
 (21, 117),
 (21, 123),
 (21, 141),
 (21, 147),
 (21, 165),
 (21, 171),
 (21, 177),
 (21, 195),
 (21, 201),
 (21, 207),
 (21, 285),
 (27, 15),
 (27, 21),
 (27, 99),
 (27, 141),
 (27, 147),
 (27, 177),
 (33, 39),
 (33, 51),
 (33, 57),
 (33, 63),
 (33, 69),
 (33, 75),
 (33, 87),
 (33, 93),
 (33, 99),
 (33, 111),
 (33, 129),
 (33, 135),
 (33, 171),
 (33, 189),
 (33, 219),
 (33, 225),
 (33, 249),
 (33, 261),
 (33, 267),
 (33, 315),
 (33, 321),
 (33, 363),
 (33, 369),
 (33, 375),
 (39, 33),
 (39, 45),
 (39, 57),
 (39, 69),
 (39, 87),
 (39, 93),
 (39, 171),
 (45, 9),
 (45, 39),
 (45, 63),
 (45, 75),
 (45, 159),
 (51, 33),
 (51, 57),
 (51, 81),
 (51, 87),
 (51, 105),
 (51, 129),
 (51, 135),
 (51, 153),
 (51, 183),
 (51, 213),
 (57, 33),
 (57, 39),
 (57, 51),
 (57, 69),
 (57, 87),
 (57, 93),
 (57, 105),
 (57, 129),
 (57, 135),
 (57, 153),
 (57, 183),
 (57, 213),
 (63, 9),
 (63, 21),
 (63, 33),
 (63, 45),
 (63, 75),
 (63, 111),
 (63, 117),
 (63, 123),
 (63, 165),
 (63, 171),
 (63, 195),
 (63, 201),
 (63, 207),
 (63, 219),
 (63, 225),
 (63, 231),
 (63, 249),
 (63, 261),
 (63, 267),
 (63, 315),
 (63, 321),
 (63, 333),
 (63, 351),
 (63, 363),
 (63, 369),
 (63, 375),
 (63, 381),
 (63, 387),
 (63, 453),
 (63, 471),
 (63, 483),
 (63, 501),
 (63, 513),
 (69, 33),
 (69, 39),
 (69, 57),
 (69, 81),
 (69, 87),
 (69, 93),
 (69, 105),
 (69, 135),
 (69, 153),
 (69, 159),
 (69, 183),
 (69, 213),
 (69, 237),
 (69, 243),
 (69, 255),
 (75, 9),
 (75, 21),
 (75, 33),
 (75, 45),
 (75, 63),
 (75, 111),
 (75, 117),
 (75, 123),
 (75, 165),
 (75, 171),
 (75, 195),
 (75, 201),
 (75, 207),
 (75, 219),
 (75, 225),
 (75, 249),
 (75, 261),
 (75, 267),
 (75, 315),
 (75, 321),
 (75, 363),
 (81, 51),
 (81, 69),
 (81, 87),
 (81, 105),
 (81, 129),
 (81, 135),
 (81, 153),
 (81, 183),
 (81, 207),
 (81, 327),
 (81, 333),
 (81, 351),
 (81, 381),
 (81, 405),
 (81, 411),
 (81, 429),
 (81, 435),
 (87, 33),
 (87, 39),
 (87, 51),
 (87, 57),
 (87, 69),
 (87, 81),
 (87, 93),
 (87, 105),
 (87, 129),
 (87, 135),
 (87, 153),
 (87, 183),
 (87, 213),
 (93, 33),
 (93, 39),
 (93, 57),
 (93, 69),
 (93, 87),
 (93, 99),
 (93, 105),
 (93, 129),
 (93, 135),
 (93, 159),
 (93, 189),
 (99, 9),
 (99, 21),
 (99, 27),
 (99, 33),
 (99, 93),
 (99, 105),
 (99, 117),
 (99, 141),
 (99, 147),
 (99, 183),
 (99, 189),
 (99, 213),
 (99, 237),
 (99, 243),
 (99, 255),
 (99, 273),
 (99, 279),
 (99, 291),
 (99, 339),
 (99, 345),
 (99, 357),
 (99, 393),
 (105, 51),
 (105, 57),
 (105, 69),
 (105, 81),
 (105, 87),
 (105, 93),
 (105, 99),
 (105, 135),
 (105, 153),
 (105, 183),
 (105, 213),
 (105, 327),
 (111, 21),
 (111, 33),
 (111, 63),
 (111, 75),
 (111, 117),
 (111, 123),
 (111, 165),
 (111, 171),
 (111, 195),
 (111, 201),
 (111, 207),
 (111, 219),
 (111, 225),
 (111, 249),
 (111, 261),
 (111, 267),
 (111, 315),
 (111, 321),
 (111, 363),
 (111, 369),
 (111, 375),
 (111, 387),
 (117, 21),
 (117, 63),
 (117, 75),
 (117, 99),
 (117, 111),
 (117, 123),
 (117, 129),
 (117, 153),
 (117, 165),
 (123, 21),
 (123, 63),
 (123, 75),
 (123, 111),
 (123, 117),
 (123, 147),
 (123, 165),
 (123, 195),
 (123, 201),
 (123, 207),
 (123, 219),
 (123, 225),
 (123, 231),
 (123, 249),
 (123, 261),
 (123, 267),
 (129, 33),
 (129, 51),
 (129, 57),
 (129, 81),
 (129, 87),
 (129, 93),
 (129, 117),
 (129, 135),
 (135, 33),
 (135, 51),
 (135, 57),
 (135, 69),
 (135, 81),
 (135, 87),
 (135, 93),
 (135, 105),
 (135, 129),
 (135, 153),
 (135, 183),
 (135, 213),
 (135, 237),
 (141, 27),
 (141, 99),
 (141, 147),
 (141, 177),
 (147, 9),
 (147, 21),
 (147, 27),
 (147, 99),
 (147, 123),
 (147, 141),
 (147, 177),
 (147, 189),
 (147, 219),
 (147, 225),
 (153, 51),
 (153, 57),
 (153, 69),
 (153, 81),
 (153, 87),
 (153, 105),
 (153, 117),
 (153, 135),
 (153, 183),
 (153, 207),
 (153, 213),
 (153, 255),
 (153, 327),
 (159, 45),
 (159, 69),
 (159, 93),
 (165, 21),
 (165, 63),
 (165, 75),
 (165, 111),
 (165, 117),
 (165, 123),
 (165, 195),
 (165, 201),
 (165, 207),
 (171, 21),
 (171, 33),
 (171, 39),
 (171, 63),
 (171, 75),
 (171, 111),
 (171, 195),
 (171, 219),
 (171, 225),
 (171, 249),
 (171, 261),
 (171, 267),
 (171, 315),
 (171, 321),
 (171, 363),
 (171, 375),
 (177, 21),
 (177, 27),
 (177, 141),
 (177, 147),
 (183, 51),
 (183, 57),
 (183, 69),
 (183, 81),
 (183, 87),
 (183, 99),
 (183, 105),
 (183, 135),
 (183, 153),
 (183, 189),
 (183, 207),
 (183, 213),
 (183, 243),
 (183, 309),
 (183, 327),
 (183, 399),
 (189, 9),
 (189, 33),
 (189, 93),
 (189, 99),
 (189, 123),
 (189, 147),
 (189, 183),
 (189, 207),
 (189, 213),
 (189, 243),
 (189, 255),
 (189, 291),
 (189, 297),
 (189, 309),
 (189, 357),
 (189, 399),
 (195, 21),
 (195, 63),
 (195, 75),
 (195, 111),
 (195, 123),
 (195, 165),
 (195, 171),
 (195, 201),
 (195, 207),
 (201, 21),
 (201, 63),
 (201, 75),
 (201, 111),
 (201, 123),
 (201, 165),
 (201, 195),
 (201, 207),
 (201, 219),
 (201, 225),
 (201, 249),
 (201, 261),
 (201, 267),
 (201, 285),
 (201, 303),
 (201, 321),
 (201, 333),
 (201, 351),
 (201, 363),
 (201, 381),
 (201, 387),
 (201, 411),
 (201, 453),
 (201, 471),
 (201, 477),
 (201, 483),
 (201, 501),
 (201, 513),
 (201, 537),
 (201, 549),
 (201, 555),
 (201, 573),
 (207, 21),
 (207, 63),
 (207, 75),
 (207, 81),
 (207, 111),
 (207, 123),
 (207, 153),
 (207, 165),
 (207, 183),
 (207, 189),
 (207, 195),
 (207, 201),
 (207, 213),
 (207, 237),
 (207, 243),
 (207, 255),
 (207, 273),
 (207, 279),
 (207, 285),
 (207, 291),
 (207, 297),
 (207, 309),
 (207, 339),
 (207, 345),
 (207, 357),
 (207, 393),
 (207, 399),
 (207, 417),
 (207, 423),
 (207, 441),
 (207, 447),
 (207, 459),
 (207, 495),
 (207, 507),
 (207, 525),
 (207, 561),
 (207, 579),
 (207, 597),
 (207, 639),
 (207, 651),
 (207, 657),
 (213, 51),
 (213, 57),
 (213, 69),
 (213, 87),
 (213, 99),
 (213, 105),
 (213, 135),
 (213, 153),
 (213, 183),
 (213, 189),
 (213, 207),
 (213, 219),
 (213, 225),
 (213, 243),
 (213, 249),
 (213, 255),
 (213, 261),
 (213, 267),
 (213, 309),
 (213, 327),
 (213, 363),
 (213, 387),
 (213, 399),
 (213, 405),
 (213, 411),
 (213, 429),
 (213, 435),
 (213, 489),
 (213, 519),
 (213, 531),
 (213, 543),
 (213, 585),
 (219, 9),
 (219, 33),
 (219, 63),
 (219, 75),
 (219, 111),
 (219, 123),
 (219, 147),
 (219, 171),
 (219, 189),
 (219, 201),
 (219, 213),
 (219, 225),
 (219, 231),
 (219, 249),
 (219, 261),
 (219, 267),
 (219, 285),
 (219, 303),
 (219, 315),
 (219, 321),
 (219, 333),
 (219, 351),
 (219, 363),
 (219, 369),
 (219, 375),
 (219, 381),
 (219, 405),
 (219, 411),
 (219, 429),
 (219, 435),
 (219, 489),
 (219, 519),
 (225, 9),
 (225, 33),
 (225, 63),
 (225, 75),
 (225, 111),
 (225, 123),
 (225, 147),
 (225, 171),
 (225, 201),
 (225, 213),
 (225, 219),
 (225, 231),
 (225, 249),
 (225, 261),
 (225, 267),
 (225, 285),
 (225, 303),
 (225, 315),
 (225, 321),
 (225, 333),
 (225, 351),
 (225, 363),
 (225, 369),
 (225, 375),
 (225, 381),
 (225, 405),
 (225, 411),
 (225, 429),
 (225, 435),
 (225, 489),
 (225, 519),
 (231, 63),
 (231, 123),
 (231, 219),
 (231, 225),
 (231, 249),
 (237, 69),
 (237, 99),
 (237, 135),
 (237, 207),
 (237, 255),
 (237, 273),
 (237, 279),
 (237, 291),
 (237, 309),
 (237, 321),
 (237, 327),
 (237, 345),
 (237, 357),
 (237, 375),
 (237, 381),
 (237, 393),
 (237, 399),
 (237, 411),
 (237, 435),
 (237, 453),
 (237, 465),
 (237, 471),
 (237, 477),
 (237, 501),
 (237, 531),
 (237, 537),
 (237, 549),
 (237, 555),
 (237, 561),
 (237, 567),
 (237, 573),
 (237, 591),
 (237, 615),
 (237, 621),
 (237, 627),
 (237, 645),
 (237, 681),
 (237, 687),
 (237, 711),
 (237, 723),
 (237, 753),
 (237, 759),
 (243, 69),
 (243, 99),
 (243, 183),
 (243, 189),
 (243, 207),
 (243, 213),
 (243, 255),
 (243, 297),
 (243, 309),
 (243, 399),
 (249, 33),
 (249, 63),
 (249, 75),
 (249, 111),
 (249, 123),
 (249, 171),
 (249, 201),
 (249, 213),
 (249, 219),
 (249, 225),
 (249, 231),
 (249, 261),
 (249, 267),
 (249, 315),
 (249, 321),
 (249, 327),
 (249, 333),
 (249, 351),
 (249, 363),
 (249, 369),
 (249, 375),
 (249, 381),
 (249, 387),
 (249, 411),
 (249, 435),
 (249, 453),
 (249, 465),
 (249, 471),
 (249, 477),
 (249, 483),
 (249, 489),
 (249, 501),
 (249, 513),
 (249, 519),
 (249, 531),
 (249, 537),
 (249, 543),
 (249, 549),
 (249, 555),
 (249, 567),
 (249, 573),
 (249, 585),
 (249, 627),
 (255, 69),
 (255, 99),
 (255, 153),
 (255, 189),
 (255, 207),
 (255, 213),
 (255, 237),
 (255, 243),
 (255, 261),
 (255, 279),
 (255, 291),
 (255, 297),
 (255, 309),
 (255, 345),
 (255, 357),
 (255, 363),
 (255, 387),
 (255, 399),
 (255, 411),
 (255, 429),
 (255, 435),
 (255, 465),
 (255, 483),
 (255, 519),
 (255, 531),
 (255, 543),
 (255, 585),
 (255, 615),
 (255, 633),
 (255, 663),
 (255, 699),
 (261, 33),
 (261, 63),
 (261, 75),
 (261, 111),
 (261, 123),
 (261, 171),
 (261, 201),
 (261, 213),
 (261, 219),
 (261, 225),
 (261, 249),
 (261, 255),
 (261, 267),
 (261, 315),
 (261, 321),
 (261, 327),
 (261, 333),
 (261, 351),
 (261, 363),
 (261, 369),
 (261, 375),
 (261, 381),
 (261, 387),
 (261, 411),
 (261, 435),
 (261, 453),
 (261, 465),
 (261, 471),
 (261, 477),
 (261, 483),
 (261, 489),
 (261, 501),
 (261, 513),
 (261, 519),
 (261, 531),
 (261, 537),
 (261, 543),
 (261, 549),
 (261, 555),
 (261, 567),
 (261, 573),
 (261, 585),
 (261, 609),
 (261, 615),
 (261, 627),
 (261, 633),
 (261, 663),
 (261, 699),
 (267, 33),
 (267, 63),
 (267, 75),
 (267, 111),
 (267, 123),
 (267, 171),
 (267, 201),
 (267, 213),
 (267, 219),
 (267, 225),
 (267, 249),
 (267, 261),
 (267, 285),
 (267, 303),
 (267, 315),
 (267, 321),
 (267, 333),
 (267, 351),
 (267, 363),
 (267, 369),
 (267, 375),
 (267, 381),
 (267, 405),
 (267, 411),
 (267, 429),
 (267, 435),
 (267, 489),
 (267, 519),
 (267, 531),
 (273, 99),
 (273, 207),
 (273, 237),
 (273, 279),
 (273, 291),
 (273, 309),
 (273, 339),
 (273, 345),
 (273, 357),
 (273, 393),
 (273, 399),
 (273, 447),
 (279, 99),
 (279, 207),
 (279, 237),
 (279, 255),
 (279, 273),
 (279, 291),
 (279, 309),
 (279, 339),
 (279, 345),
 (279, 357),
 (279, 393),
 (279, 399),
 (279, 417),
 (279, 447),
 (285, 21),
 (285, 201),
 (285, 207),
 (285, 219),
 (285, 225),
 (285, 267),
 (285, 303),
 (285, 333),
 (285, 351),
 (291, 99),
 (291, 189),
 (291, 207),
 (291, 237),
 (291, 255),
 (291, 273),
 (291, 279),
 (291, 297),
 (291, 309),
 (291, 345),
 (291, 357),
 (291, 399),
 (291, 465),
 (297, 189),
 (297, 207),
 (297, 237),
 (297, 243),
 (297, 255),
 (297, 291),
 (297, 309),
 (297, 357),
 (297, 399),
 (297, 465),
 (303, 201),
 (303, 219),
 (303, 225),
 (303, 267),
 (303, 285),
 (303, 333),
 (303, 351),
 (303, 381),
 (309, 183),
 (309, 189),
 (309, 207),
 (309, 213),
 (309, 237),
 (309, 243),
 (309, 255),
 (309, 273),
 (309, 279),
 (309, 291),
 (309, 297),
 (309, 339),
 (309, 345),
 (309, 357),
 (309, 393),
 (309, 399),
 (309, 417),
 (309, 423),
 (309, 441),
 (309, 447),
 (309, 459),
 (309, 495),
 (309, 507),
 (309, 525),
 (309, 561),
 (309, 579),
 (309, 597),
 (315, 33),
 (315, 63),
 (315, 75),
 (315, 111),
 (315, 171),
 (315, 219),
 (315, 225),
 (315, 249),
 (315, 261),
 (315, 267),
 (315, 321),
 (315, 363),
 (321, 33),
 (321, 63),
 (321, 75),
 (321, 111),
 (321, 171),
 (321, 201),
 (321, 219),
 (321, 225),
 (321, 237),
 (321, 249),
 (321, 261),
 (321, 267),
 (321, 315),
 (321, 327),
 (321, 333),
 (321, 351),
 (321, 363),
 (321, 369),
 (321, 375),
 (321, 381),
 (321, 387),
 (321, 393),
 (321, 429),
 (321, 453),
 (321, 459),
 (321, 471),
 (321, 477),
 (321, 483),
 (321, 501),
 (321, 507),
 (321, 519),
 (321, 525),
 (321, 537),
 (321, 543),
 (321, 561),
 (321, 579),
 (321, 585),
 (321, 603),
 (321, 669),
 (321, 675),
 (321, 681),
 (321, 687),
 (321, 729),
 (321, 735),
 (321, 765),
 (321, 771),
 (321, 777),
 (321, 807),
 (321, 819),
 (321, 855),
 (321, 873),
 (321, 903),
 (327, 81),
 (327, 105),
 (327, 153),
 (327, 183),
 (327, 213),
 (327, 237),
 (327, 249),
 (327, 261),
 (327, 321),
 (327, 363),
 (327, 375),
 (327, 381),
 (327, 387),
 (327, 453),
 (327, 471),
 (327, 477),
 (327, 483),
 (327, 501),
 (327, 537),
 (327, 549),
 (327, 555),
 (327, 567),
 (327, 573),
 (327, 591),
 (327, 621),
 (327, 627),
 (327, 645),
 (333, 63),
 (333, 81),
 (333, 201),
 (333, 219),
 (333, 225),
 (333, 249),
 (333, 261),
 (333, 267),
 (333, 285),
 (333, 303),
 (333, 321),
 (333, 351),
 (333, 363),
 (333, 381),
 (333, 387),
 (333, 453),
 (333, 471),
 (333, 477),
 (333, 483),
 (333, 501),
 (333, 513),
 (333, 537),
 (333, 549),
 (333, 555),
 (339, 99),
 (339, 207),
 (339, 273),
 (339, 279),
 (339, 309),
 (339, 345),
 (339, 357),
 (339, 375),
 (339, 393),
 (339, 399),
 (339, 417),
 ...]

In [70]:
import pandas as pd

filepath = "./temp/pair_27_15.csv" # 15 (attacker), 27 (21 also works)
filepath = "./temp/pair_15_27.csv" 

# 21-27 is both benign
# filepath = "./temp/pair_27_15.csv" 
filepath = "./temp/pair_21_27.csv" 

out1 = pd.read_csv(filepath)
out1

,RecieverID,SenderID,rcvTime,RelX,RelY,MssgCount,dVx,dVy,dAx,dAy,AttkType
0,27,21,25208.812287,4.239470,234.448777,1,0.000000,0.000000,0.000000,0.000000,0
1,27,21,25209.812282,4.599074,232.714984,1,0.377664,0.672683,0.246643,2.631775,0
2,27,21,25210.812278,4.719203,229.062737,1,0.043414,2.715465,0.174078,1.857482,0
3,27,21,25211.812286,5.438146,223.477601,1,0.564945,4.545399,0.157102,1.676271,0
4,27,21,25212.812282,5.752124,216.010266,1,0.383778,6.659004,0.173455,1.850824,0
5,27,21,25213.812277,6.807024,206.528351,1,0.954483,8.375149,0.214574,2.289469,0
6,27,21,25214.812285,7.992645,194.973552,1,0.864906,10.556309,0.194339,2.073674,0
7,27,21,25215.812281,9.002928,181.998001,1,1.104056,12.658818,0.041417,1.367491,0
8,27,21,25216.812276,9.923550,168.938606,1,1.251552,13.076186,0.145520,0.291952,0
9,27,21,25217.812284,10.806697,155.905559,1,0.883907,13.023443,0.042083,0.567530,0
10,27,21,25218.812279,11.727050,142.876966,1,0.920392,13.019990,0.001833,0.024640,0
11,27,21,25219.812286,12.649435,129.851949,1,1.098922,13.015631,0.001820,0.024539,0
12,27,21,25220.812281,13.686422,116.799448,1,1.053665,13.088639,0.009928,0.133891,0
13,27,21,25221.812276,14.563606,103.741215,1,1.031437,13.072373,0.014173,0.191236,0
14,27,21,25222.812283,15.466856,90.688100,1,0.945511,13.055769,0.016363,0.220674,0
15,27,21,25223.812278,16.600550,77.646783,1,1.134417,13.048415,0.018208,0.245576,0
16,27,21,25224.812285,17.674024,64.607208,1,0.927270,12.999886,0.002460,0.033176,0
17,27,21,25225.812280,18.749442,51.557541,1,1.010846,13.053669,0.008817,0.118901,0
18,27,21,25226.812274,19.865154,38.489738,1,1.039298,13.069826,0.011012,0.148512,0
19,27,21,25227.812281,20.758032,25.453036,1,0.911832,13.057707,0.027564,0.371723,0
20,27,21,25228.812275,21.864494,12.408548,1,1.005751,13.039514,0.018163,0.244939,0
21,27,21,25229.812283,23.118658,0.557540,1,1.148377,12.993794,0.288332,0.199797,0
22,27,21,25230.812277,24.460143,13.444926,1,1.220517,12.858205,0.043122,0.015304,0
23,27,21,25231.812284,25.732441,26.386370,1,1.276845,12.928115,0.250959,0.259683,0
24,27,21,25232.812279,27.375226,39.394090,1,1.719951,13.009347,0.056454,0.458876,0
25,27,21,25233.812279,28.910036,52.328812,1,1.468524,12.974682,0.059461,0.246677,0
26,27,21,25234.812280,30.475950,65.308694,1,1.669362,12.928681,0.023788,0.182948,0
27,27,21,25235.812280,32.706777,78.230895,1,1.830389,13.001352,0.531380,0.639565,0
28,27,21,25236.812275,34.704010,91.112192,1,1.922758,12.843170,0.360959,0.563526,0
29,27,21,25237.812283,36.379947,104.039742,1,1.731437,12.912309,0.054876,0.136546,0
30,27,21,25238.812278,38.223506,116.982838,1,1.890631,12.959558,0.039004,0.171918,0
31,27,21,25239.812286,40.061473,129.886946,1,1.778617,12.898526,0.026249,0.067673,0
32,27,21,25240.812281,42.094043,142.804755,1,1.839351,12.921855,0.007094,0.048488,0
33,27,21,25241.812276,43.907730,155.766531,1,2.062049,12.961791,0.052423,0.358313,0
34,27,21,25242.812284,45.697413,168.682530,1,1.841807,12.945304,0.066358,0.453562,0
35,27,21,25243.812280,47.853105,181.608889,1,2.083549,12.931119,0.046488,0.208271,0
36,27,21,25244.812275,49.434264,194.512292,1,1.654231,12.880279,0.037166,0.244341,0
37,27,21,25245.812284,51.289872,207.420496,1,1.945692,12.921078,0.019941,0.131079,0
38,27,21,25246.812279,51.806000,220.482392,1,1.907008,12.905841,0.022511,0.147998,0
39,27,21,25247.812275,50.614625,234.679178,1,2.038407,12.962642,0.051099,0.335943,0
40,27,21,25248.812284,51.579843,252.849747,1,2.113171,12.923550,0.018864,0.124000,0
41,27,21,25249.812280,54.108294,273.454925,1,1.960293,12.867623,0.128627,0.133941,0
42,27,21,25250.812278,56.588922,296.257508,1,1.780862,12.947864,0.029384,0.204301,0
43,27,21,25251.812277,59.376133,321.191139,1,1.839974,12.911574,0.096310,0.669488,0
44,27,21,25252.812276,62.367357,346.957481,1,1.924570,12.978954,0.087788,0.610222,0

In [71]:
filepath = "./temp/pair_27_21.csv" 

out = pd.read_csv(filepath)
outfilepath = "./temp/pair_21_27.csv" 

out2 = pd.read_csv(filepath)
out2

,RecieverID,SenderID,rcvTime,RelX,RelY,MssgCount,dVx,dVy,dAx,dAy,AttkType
0,21,27,25208.925714,4.239470,234.448777,1,0.000000,0.000000,0.000000,0.000000,0
1,21,27,25209.925709,4.599074,232.714984,1,0.117604,0.001064,0.000000,0.000000,0
2,21,27,25210.925705,4.719203,229.062737,1,0.011102,0.000255,0.000000,0.000000,0
3,21,27,25211.925713,5.438146,223.477601,1,0.056696,0.001520,0.000000,0.000000,0
4,21,27,25212.925708,5.752124,216.010266,1,0.145801,0.002623,0.000000,0.000000,0
5,21,27,25213.925704,6.807024,206.528351,1,0.003354,0.000460,0.000000,0.000000,0
6,21,27,25214.925712,7.992645,194.973552,1,0.227482,0.003653,0.000000,0.000000,0
7,21,27,25215.925707,9.002928,181.998001,1,0.080063,0.002192,0.000000,0.000000,0
8,21,27,25216.925702,9.923550,168.938606,1,0.245562,0.001361,0.000000,0.000000,0
9,21,27,25217.925710,10.806697,155.905559,1,0.001749,0.003732,0.000000,0.000000,0
10,21,27,25218.925705,11.727050,142.876966,1,0.000520,0.002076,0.000000,0.000000,0
11,21,27,25219.925713,12.649435,129.851949,1,0.177723,0.006593,0.000000,0.000000,0
12,21,27,25220.925708,13.686422,116.799448,1,0.014610,0.008259,0.000000,0.000000,0
13,21,27,25221.925702,14.563606,103.741215,1,0.153769,0.007673,0.000000,0.000000,0
14,21,27,25222.925710,15.466856,90.688100,1,0.041927,0.001848,0.000000,0.000000,0
15,21,27,25223.925704,16.600550,77.646783,1,0.000119,0.001079,0.000000,0.000000,0
16,21,27,25224.925712,17.674024,64.607208,1,0.144062,0.010804,0.000000,0.000000,0
17,21,27,25225.925706,18.749442,51.557541,1,0.064707,0.002172,0.000000,0.000000,0
18,21,27,25226.925713,19.865154,38.489738,1,0.076541,0.000322,0.000000,0.000000,0
19,21,27,25227.925707,20.758032,25.453036,1,0.017446,0.000653,0.000000,0.000000,0
20,21,27,25228.925715,21.864494,12.408548,1,0.100129,0.002881,0.000000,0.000000,0
21,21,27,25229.925709,23.118658,0.557540,1,0.043958,0.003401,0.000000,0.000000,0
22,21,27,25230.925703,24.460143,13.444926,1,0.096347,0.007262,0.000000,0.000000,0
23,21,27,25231.925711,25.732441,26.386370,1,0.148288,0.003651,0.000000,0.000000,0
24,21,27,25232.925711,27.375226,39.394090,1,0.075935,0.008365,0.000000,0.000000,0
25,21,27,25233.925712,28.910036,52.328812,1,0.025524,0.004144,0.000000,0.000000,0
26,21,27,25234.925712,30.475950,65.308694,1,0.109604,0.003853,0.000000,0.000000,0
27,21,27,25235.925713,32.706777,78.230895,1,0.193958,0.000986,0.000000,0.000000,0
28,21,27,25236.925708,34.704010,91.112192,1,0.204571,0.000582,0.000000,0.000000,0
29,21,27,25237.925702,36.379947,104.039742,1,0.095170,0.005089,0.000000,0.000000,0
30,21,27,25238.925710,38.223506,116.982838,1,0.011223,0.005271,0.000000,0.000000,0
31,21,27,25239.925705,40.061473,129.886946,1,0.039334,0.006336,0.000000,0.000000,0
32,21,27,25240.925714,42.094043,142.804755,1,0.192944,0.005927,0.000000,0.000000,0
33,21,27,25241.925709,43.907730,155.766531,1,0.247386,0.006656,0.000000,0.000000,0
34,21,27,25242.925704,45.697413,168.682530,1,0.047479,0.002445,0.000000,0.000000,0
35,21,27,25243.925712,47.853105,181.608889,1,0.034649,0.005864,0.000000,0.000000,0
36,21,27,25244.925708,49.434264,194.512292,1,0.075877,0.004688,0.000000,0.000000,0
37,21,27,25245.925703,51.289872,207.420496,1,0.088903,0.005124,0.000000,0.000000,0
38,21,27,25246.925712,51.806000,220.482392,1,0.176314,0.049782,1.366006,0.098564,0
39,21,27,25247.925708,50.614625,234.679178,1,2.265206,0.632084,1.878618,0.983861,0
40,21,27,25248.925704,51.579843,252.849747,1,2.778796,2.704461,2.373235,4.104134,0
41,21,27,25249.925713,54.108294,273.454925,1,0.249982,6.663126,1.431553,2.370985,0
42,21,27,25250.925711,56.588922,296.257508,1,0.618006,8.722248,0.179701,2.425049,0
43,21,27,25251.925710,59.376133,321.191139,1,0.874082,11.058451,0.211460,2.853660,0

In [ ]:
for i in range((min(len(out1['rcvTime']), len(out2['rcvTime'])))):
    fst = out1['rcvTime'][i]
    snd = out2['rcvTime'][i]

    fstx = out1["RelX"][i]
    sndx = out2["RelX"][i]
    if (snd < fst + 0.11):
        if (fstx == sndx):
            print("yay!")
        else:
            print(" :( )")
    else:
        print(snd - fst)

# Takeaway: there's a time offset in "receive time", but their

yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!
yay!

In [67]:
import numpy as np
import math
fr = 10
sec = 11
print(out['dVx'][sec] * math.pow((out['rcvTime'][sec] - out['rcvTime'][fr]), 2)
                                 ) # over time
print(out['RelX'][sec]-out['RelX'][fr]) # actual change

0.1777252835971731
0.9779832307582703